### ISSUE TITLE
Initial configuration checklist

### ISSUE THREAD

**Issue by mateomh** [mateomh/Rexy-Run-thegame#1]
- [x] Create the **.github/worflows** folder
- [x] Create the **linters.yml** inside the workflows folder
- [x] Create the **.eslintrc.json** file in the root folder
- [x] Create the **.stylelintrc.json** file in the root folder.
- [x] Install linters locally
- [x] Create the **.gitignore** file with the **node_modules/** inside it
- [x] Run **npm init** to create the package.json file.
- [x] If using webpack install it in the development enviroment with **npm install webpack webpack-cli --save-dev**.
- [x] Create the **webpack.config.js** file for the webpack configuration.
- [x] Create the **src** and **dist** folders and configure the entry and outputs in the webpack file.
